# Generated by Django 6.0 on 2025-12-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Duration of the exam in minutes."
                    ),
                ),
                (
                    "is_realtime",
                    models.BooleanField(
                        default=True, help_text="If false, it's a practice test."
                    ),
                ),
                ("show_score_immediately", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Question"),
                            ("TEXT", "Short Answer Text"),
                        ],
                        default="MCQ",
                        max_length=10,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of options for MCQs.",
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        help_text="The correct answer (e.g., 'A' for MCQ, or text for TEXT type)."
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessment.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessment.exam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.question",
                    ),
                ),
                (
                    "user_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assessment.userattempt",
                    ),
                ),
            ],
        ),
        # NOTE: Removed original UniqueConstraint that referenced a joined field
        # (exam__is_realtime) because SQLite does not support joined field
        # references in conditional constraints. The final, compatible
        # constraint is added later in migration 0005 (using a local field).
    ]
