# Generated by Django 6.0 on 2025-12-07 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_learningprogress_resourceview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userattempt",
            name="unique_realtime_attempt",
        ),
        migrations.AddConstraint(
            model_name="userattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam__is_realtime", False)),
                fields=("user", "exam"),
                name="unique_realtime_attempt",
            ),
        ),
    ]
