# Generated by Django 6.0 on 2025-12-07 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_learningprogress_resourceview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # This migration previously removed/added a constraint that referenced
        # a joined field (`exam__is_realtime`). That constraint has been
        # removed from earlier migrations to ensure compatibility with
        # SQLite. No operations are required here.
    ]
