# Generated by Django 6.0 on 2025-12-07 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_userattempt_exam_is_realtime"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userattempt",
            name="unique_realtime_attempt",
        ),
        migrations.RenameField(
            model_name="userattempt",
            old_name="exam_is_realtime",
            new_name="is_practice_mode",
        ),
        migrations.AddConstraint(
            model_name="userattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_practice_mode", True)),
                fields=("user", "exam"),
                name="unique_practice_attempt",
            ),
        ),
    ]
