# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_remove_userattempt_unique_realtime_attempt_and_more"),
        ("courses", "0002_course_school_course_teacher_announcement_and_more"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_inter_school",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_exams",
                to="school.school",
            ),
        ),
        migrations.CreateModel(
            name="ManualGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("max_score", models.IntegerField(default=100)),
                ("editable_by_teacher", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_manual_grades",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_manual_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_manual_grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course", "assignment_name")},
            },
        ),
    ]
