# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "official_lat",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "official_lon",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("geo_fence_radius_m", models.IntegerField(default=50)),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FRSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enforce_teacher_login_fr", models.BooleanField(default=False)),
                ("enforce_exam_start_fr", models.BooleanField(default=False)),
                ("enforce_retrieval_fr", models.BooleanField(default=False)),
                (
                    "similarity_threshold",
                    models.FloatField(
                        default=0.8, help_text="Value between 0.5 and 1.0"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fr_settings",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "FR Settings",
                "verbose_name_plural": "FR Settings",
            },
        ),
        migrations.CreateModel(
            name="SystemSound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=50, unique=True)),
                ("audio_file", models.FileField(upload_to="system_sounds/")),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "unique_together": {("school", "name")},
            },
        ),
    ]
