# Generated by Django 6.0 on 2025-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_remove_userattempt_unique_realtime_attempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userattempt",
            name="exam_is_realtime",
            field=models.BooleanField(default=False),
        ),
    ]
