# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "enforce_face_scan",
                    models.BooleanField(
                        default=True,
                        help_text="Requires a facial scan before starting the exam.",
                    ),
                ),
                (
                    "enforce_location_check",
                    models.BooleanField(
                        default=True,
                        help_text="Requires geolocation verification before and during the exam.",
                    ),
                ),
                (
                    "max_allowed_violations",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum allowed security violations before automatic submission.",
                    ),
                ),
                (
                    "requires_registration",
                    models.BooleanField(
                        default=True,
                        help_text="Must students register and be shortlisted before taking this exam?",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        default="Ndakaru",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                            ("DISQUALIFIED", "Disqualified"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_passed", models.BooleanField(default=False)),
                ("total_violations", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="SecurityViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("FACE_MISMATCH", "Facial Recognition Mismatch"),
                            ("LOCATION_DRIFT", "Location Drift/Change"),
                            ("BROWSER_TAB_CHANGE", "Browser Tab/Focus Change"),
                            ("THIRD_PARTY_ACCESS", "Unauthorized Third Party Access"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "proctoring_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="proctoring_evidence/"
                    ),
                ),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="exams.examattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                (
                    "shortlist_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for REJECTED status (e.g., 'Fees not paid').",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"profile__role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Exam Registrations",
                "unique_together": {("student", "exam")},
            },
        ),
    ]
