
// 1. Define Colors First
const r = "\x1b[1;31m"; // Red Bold
const g = "\x1b[32m";   // Green
const w = "\x1b[1m";    // White Bold
const x = "\x1b[0m";    // Reset

// 2. Create the Time variable
const time = new Date().toLocaleTimeString('en-GB', { hour12: false });

// Syntax: Color + Text + Reset
console.log(`${r}[${time}]${x} ${g}♦️♦️♦️♦️ Broadcasting script is running 🪁🪁🪁 ♦️♦️♦️♦️${x}`);

const fs = require('fs');
const { delay } = require('../lib/helper');

module.exports = async (sock, from, command, args, msg) => {
    if (command !== 'bc' && command !== 'broadcast') return;

    const broadcastMsg = args.join(' ');
    if (!broadcastMsg) return sock.sendMessage(from, { text: "❌ Usage: .bc [Your Message]" });

    let recipients = [];

    // --- 1. DETERMINE TARGETS ---
    const isGroupBc = msg.key.remoteJid.endsWith('@g.us');

    if (isGroupBc) {
        // Broadcast to specific group members
        const metadata = await sock.groupMetadata(from);
        recipients = metadata.participants.map(p => p.id);
        await sock.sendMessage(from, { text: `🚀 Starting Group Broadcast to ${recipients.length} members...` });
    } else {
        // Broadcast to all saved contacts in contacts.json
        const contacts = JSON.parse(fs.readFileSync('./database/contacts.json', 'utf-8') || "[]");
        recipients = contacts.map(c => c.jid);
        await sock.sendMessage(from, { text: `🚀 Starting Contact Broadcast to ${recipients.length} users...` });
    }

    // --- 2. BROADCAST LOGIC WITH ANTI-BAN ---
    let count = 0;
    for (let jid of recipients) {
        try {
            // Batching: Every 150 messages, wait 1 minute
            if (count > 0 && count % 150 === 0) {
                console.log(`⏳ Batch limit reached. Sleeping for 60s...`);
                await delay(60000); 
            }

            // Interval: 5 seconds between every single message
            await delay(5000); 

            await sock.sendMessage(jid, { 
                text: broadcastMsg + "\n\n_Generated by Z-Bot_ 🤖",
                // Add a "Broadcast ID" to make AI recognize replies
                contextInfo: { externalAdReply: { title: "OFFICIAL BROADCAST", body: "Reply to chat with AI" }}
            });

            count++;
            console.log(`✅ [BC] Sent to ${jid} (${count}/${recipients.length})`);
        } catch (e) {
            console.error(`❌ Failed to send to ${jid}`);
        }
    }

    await sock.sendMessage(from, { text: `✅ Broadcast Complete! Sent to ${count} recipients.` });
};
