# Generated by Django 6.0 on 2025-12-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("ADMINISTRATOR", "Administrator"),
                        ],
                        default="STUDENT",
                        max_length=15,
                        verbose_name="Account Role",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Title (e.g., BSc Student)",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="User Biography")),
                (
                    "follows",
                    models.ManyToManyField(
                        blank=True, related_name="followers", to="users.userprofile"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
