# Generated by Django 6.0 on 2025-12-16 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FRSettings",
            fields=[
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="school.school",
                    ),
                ),
                ("enforce_teacher_login_fr", models.BooleanField(default=False)),
                ("enforce_exam_start_fr", models.BooleanField(default=True)),
                ("enforce_retrieval_fr", models.BooleanField(default=True)),
                (
                    "similarity_threshold",
                    models.DecimalField(decimal_places=2, default=0.85, max_digits=3),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="assessment_number",
            field=models.CharField(
                blank=True,
                help_text="Unique ID generated upon first exam registration.",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_students",
                to="school.class",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="facial_template",
            field=models.BinaryField(
                blank=True,
                help_text="Secured biometric template for facial recognition.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_whitelisted",
            field=models.BooleanField(
                default=True,
                help_text="If False, the assessment number is blocked from starting exams.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="passport_photo",
            field=models.ImageField(
                blank=True,
                help_text="High-resolution photo for identity verification.",
                null=True,
                upload_to="user_passport_photos/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="private_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_in_school",
                to="school.school",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="xp",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("ADMINISTRATOR", "Administrator"),
                    ("PARENT", "Parent"),
                ],
                default="STUDENT",
                max_length=15,
                verbose_name="Account Role",
            ),
        ),
    ]
