"""
Django settings for mwalimu_boney_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta # Don't forget this import at the top
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1pksg51o#v9^k8xai%066^_kcezz$vy$pz44n7med6%qeuu_jm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    # ... other apps
    "channels", # Add this near the top
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ... Third-party apps
    'rest_framework',
    'corsheaders',
    'djoser',
    # Your apps
    'courses',
    'users',
    'chat',
    'assessment',
    'notifications',
    'school',
    'reports',
    'communications',
    'gamification',
    'progress',
    'exams',
    'ai_features',
      
    # Project-level app config to import centralized admin registrations
    'mwalimu_boney_backend.apps.MwalimuBoneyBackendConfig',
   
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # MUST be placed high up
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# Configure GDAL
import os

# 1. Path to your QGIS bin directory
QGIS_BIN = r'C:\Program Files\QGIS 3.44.5\bin'

if os.path.exists(QGIS_BIN):
    # This is critical for Python 3.8+ on Windows
    os.add_dll_directory(QGIS_BIN)
    
    # Force these specific variables
    GDAL_LIBRARY_PATH = os.path.join(QGIS_BIN, 'gdal312.dll')
    GEOS_LIBRARY_PATH = os.path.join(QGIS_BIN, 'geos_c.dll')
    
    # Data folders
    os.environ['PROJ_LIB'] = r'C:\Program Files\QGIS 3.44.5\share\proj'
    os.environ['GDAL_DATA'] = r'C:\Program Files\QGIS 3.44.5\share\gdal'

# During development, allow all origins for simplicity. 
# In production, change this to a specific list of domains (e.g., 'http://yourreactapp.com')
CORS_ALLOW_ALL_ORIGINS = True

# This setting allows specific origins to make cross-site HTTP requests.
CORS_ALLOWED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
    
    # Include your frontend development URL here, e.g.:
    # "http://localhost:3000",
]

# Allow credentials (cookies/tokens) to be sent cross-origin
CORS_ALLOW_CREDENTIALS = True



# --- CSRF Trusted Origins Configuration ---
# This list specifies origins that are trusted for CSRF protection.
CSRF_TRUSTED_ORIGINS = [
    # Required for Django to accept POST/PUT/DELETE requests from itself
    'https://localhost:8000',
    'http://localhost:8000',
    
    # Add the origin of your frontend application if it's separate (e.g., React on port 3000)
    # Example: 'http://localhost:3000',
    # Example: 'https://staging.yourdomain.com',
]

# If you are using Django REST Framework and testing with API clients 
# (like Postman), you might need to relax this for development, but 
# CSRF_TRUSTED_ORIGINS is the correct fix for browser-based requests.

{
    # ... other settings ...
    "python.analysis.extraPaths": [
        "./"
    ]
}

ROOT_URLCONF = "mwalimu_boney_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ... other settings

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # SessionAuth is good for admin, but JWT is required for the frontends
        'rest_framework.authentication.SessionAuthentication', 
        
        # This makes JWT the default method for securing your API endpoints
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Simple JWT Configuration (Optional, for custom settings like token lifetime)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    # ... other settings
}

# --- DJOSER/SIMPLE JWT SETTINGS ---
DJOSER = {
    # Specifies the JWT authentication backend
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False, # Set to True if you want email verification
    'SERIALIZERS': {'current_user': 'users.serializers.UserProfileSerializer',}, # Can be used to override default serializers
}

CHANNEL_LAYERS = {
    'default': {
        # Use the in-memory backend for Codespaces/development ease
        # 'BACKEND': 'channels.layers.InMemoryChannelLayer', 
        
        # For production, switch to:
        'BACKEND': 'channels_redis.pubsub.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)], 
        },
    },
}

WSGI_APPLICATION = "mwalimu_boney_backend.wsgi.application"

# 2. Specify the ASGI application
ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# FILE: project_root/settings.py (Add to the bottom)

# --- CELERY CONFIGURATION ---
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # Use database 0
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1' # Use database 1 for results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi' # Or your local timezone
CELERY_ENABLE_UTC = False